"""empty message

Revision ID: 230a7758f578
Revises: 56266fea47a8
Create Date: 2020-02-21 21:46:44.167814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230a7758f578'
down_revision = '56266fea47a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venue_genres_venue_id_fkey', 'venue_genres', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genres', 'venues', ['venue_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genres', type_='foreignkey')
    op.create_foreign_key('venue_genres_venue_id_fkey', 'venue_genres', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###
