"""Added seeking_venue and seeking_description properties to Artist model

Revision ID: b7883bb1c94e
Revises: e2ad889d9f75
Create Date: 2020-02-20 23:48:42.308243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7883bb1c94e'
down_revision = 'e2ad889d9f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
